[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 10000000
remappings = [
    "@openzeppelin/contracts-legacy/=lib/stablecoin-evm/node_modules/@openzeppelin/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@era-contracts/=lib/usdc-bridge/node_modules/era-contracts/"
]
fs_permissions = [
    { access = "read", path = "./lib/stablecoin-evm/artifacts" },
    { access = "read", path = "./lib/stablecoin-evm/cached_artifacts" },
    { access = "read", path = "./lib/stablecoin-evm/verification_artifacts" },
    { access = "read", path = "./lib/usdc-bridge/out" },
    { access = "read", path = "./out" },
    { access = "read-write", path = "./broadcast" },
    { access = "read-write", path = "./deployments" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
